"""Chat state machine events."""

from enum import Enum


class ChatStatusEvent(Enum):
    """Chat processing status events."""
    VALIDATE_SUCCESS = "VALIDATE_SUCCESS"
    VALIDATE_FAILURE = "VALIDATE_FAILURE"
    ANONYMISE_SUCCESS = "ANONYMISE_SUCCESS"
    ANONYMISE_FAILURE = "ANONYMISE_FAILURE"
    PROCESS_SUCCESS = "PROCESS_SUCCESS"
    PROCESS_FAILURE = "PROCESS_FAILURE"
    DEANONYMISE_SUCCESS = "DEANONYMISE_SUCCESS"
    DEANONYMISE_FAILURE = "DEANONYMISE_FAILURE"
    COMPLETE_SUCCESS = "COMPLETE_SUCCESS"
