version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/__pycache__
      - /app/backend/src/__pycache__
    env_file:
      - .env.docker
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - tiktok-network
    restart: unless-stopped

  # Redis for Caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tiktok-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Frontend with Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - tiktok-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  tiktok-network:
    driver: bridge
