services:
  rag-llm:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: llm-con
    env_file: .env
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
